/*
 * This file is generated by jOOQ.
 */
package cn.qlq.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ICountry extends Serializable {

    /**
     * Setter for <code>test1.country.id</code>.
     */
    public void setId(Integer value);

    /**
     * Getter for <code>test1.country.id</code>.
     */
    public Integer getId();

    /**
     * Setter for <code>test1.country.countryname</code>.
     */
    public void setCountryname(String value);

    /**
     * Getter for <code>test1.country.countryname</code>.
     */
    public String getCountryname();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ICountry
     */
    public void from(cn.qlq.jooq.tables.interfaces.ICountry from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ICountry
     */
    public <E extends cn.qlq.jooq.tables.interfaces.ICountry> E into(E into);
}
