/*
 * This file is generated by jOOQ.
 */
package cn.qlq.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IHibernateSequence extends Serializable {

    /**
     * Setter for <code>test1.hibernate_sequence.next_val</code>.
     */
    public void setNextVal(Long value);

    /**
     * Getter for <code>test1.hibernate_sequence.next_val</code>.
     */
    public Long getNextVal();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IHibernateSequence
     */
    public void from(cn.qlq.jooq.tables.interfaces.IHibernateSequence from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IHibernateSequence
     */
    public <E extends cn.qlq.jooq.tables.interfaces.IHibernateSequence> E into(E into);
}
