/*
 * This file is generated by jOOQ.
 */
package cn.qlq.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IMpUser extends Serializable {

    /**
     * Setter for <code>test1.mp_user.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>test1.mp_user.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>test1.mp_user.age</code>.
     */
    public void setAge(Integer value);

    /**
     * Getter for <code>test1.mp_user.age</code>.
     */
    public Integer getAge();

    /**
     * Setter for <code>test1.mp_user.deleted</code>.
     */
    public void setDeleted(Integer value);

    /**
     * Getter for <code>test1.mp_user.deleted</code>.
     */
    public Integer getDeleted();

    /**
     * Setter for <code>test1.mp_user.email</code>.
     */
    public void setEmail(String value);

    /**
     * Getter for <code>test1.mp_user.email</code>.
     */
    public String getEmail();

    /**
     * Setter for <code>test1.mp_user.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>test1.mp_user.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>test1.mp_user.unique_code</code>.
     */
    public void setUniqueCode(String value);

    /**
     * Getter for <code>test1.mp_user.unique_code</code>.
     */
    public String getUniqueCode();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IMpUser
     */
    public void from(cn.qlq.jooq.tables.interfaces.IMpUser from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IMpUser
     */
    public <E extends cn.qlq.jooq.tables.interfaces.IMpUser> E into(E into);
}
