/*
 * This file is generated by jOOQ.
 */
package cn.qlq.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ISystemShiroRolePermissions extends Serializable {

    /**
     * Setter for <code>test1.system_shiro_role_permissions.role_id</code>.
     */
    public void setRoleId(Integer value);

    /**
     * Getter for <code>test1.system_shiro_role_permissions.role_id</code>.
     */
    public Integer getRoleId();

    /**
     * Setter for <code>test1.system_shiro_role_permissions.permissions_id</code>.
     */
    public void setPermissionsId(Integer value);

    /**
     * Getter for <code>test1.system_shiro_role_permissions.permissions_id</code>.
     */
    public Integer getPermissionsId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ISystemShiroRolePermissions
     */
    public void from(cn.qlq.jooq.tables.interfaces.ISystemShiroRolePermissions from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ISystemShiroRolePermissions
     */
    public <E extends cn.qlq.jooq.tables.interfaces.ISystemShiroRolePermissions> E into(E into);
}
