/*
 * This file is generated by jOOQ.
 */
package cn.qlq.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ISystemShiroUserRoles extends Serializable {

    /**
     * Setter for <code>test1.system_shiro_user_roles.shiro_user_id</code>.
     */
    public void setShiroUserId(Integer value);

    /**
     * Getter for <code>test1.system_shiro_user_roles.shiro_user_id</code>.
     */
    public Integer getShiroUserId();

    /**
     * Setter for <code>test1.system_shiro_user_roles.roles_id</code>.
     */
    public void setRolesId(Integer value);

    /**
     * Getter for <code>test1.system_shiro_user_roles.roles_id</code>.
     */
    public Integer getRolesId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ISystemShiroUserRoles
     */
    public void from(cn.qlq.jooq.tables.interfaces.ISystemShiroUserRoles from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ISystemShiroUserRoles
     */
    public <E extends cn.qlq.jooq.tables.interfaces.ISystemShiroUserRoles> E into(E into);
}
