/*
 * This file is generated by jOOQ.
 */
package cn.qlq.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ISystemShiroUser extends Serializable {

    /**
     * Setter for <code>test1.system_shiro_user.id</code>.
     */
    public void setId(Integer value);

    /**
     * Getter for <code>test1.system_shiro_user.id</code>.
     */
    public Integer getId();

    /**
     * Setter for <code>test1.system_shiro_user.password</code>.
     */
    public void setPassword(String value);

    /**
     * Getter for <code>test1.system_shiro_user.password</code>.
     */
    public String getPassword();

    /**
     * Setter for <code>test1.system_shiro_user.username</code>.
     */
    public void setUsername(String value);

    /**
     * Getter for <code>test1.system_shiro_user.username</code>.
     */
    public String getUsername();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ISystemShiroUser
     */
    public void from(cn.qlq.jooq.tables.interfaces.ISystemShiroUser from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ISystemShiroUser
     */
    public <E extends cn.qlq.jooq.tables.interfaces.ISystemShiroUser> E into(E into);
}
