/*
 * This file is generated by jOOQ.
 */
package cn.qlq.jooq.tables.interfaces;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IUsercountry extends Serializable {

    /**
     * Setter for <code>test1.usercountry.userid</code>.
     */
    public void setUserid(Integer value);

    /**
     * Getter for <code>test1.usercountry.userid</code>.
     */
    public Integer getUserid();

    /**
     * Setter for <code>test1.usercountry.countryid</code>.
     */
    public void setCountryid(Integer value);

    /**
     * Getter for <code>test1.usercountry.countryid</code>.
     */
    public Integer getCountryid();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IUsercountry
     */
    public void from(cn.qlq.jooq.tables.interfaces.IUsercountry from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IUsercountry
     */
    public <E extends cn.qlq.jooq.tables.interfaces.IUsercountry> E into(E into);
}
