/*
 * This file is generated by jOOQ.
 */
package cn.qlq.jooq.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IUser2 extends Serializable {

    /**
     * Setter for <code>test1.user2.id</code>.
     */
    public void setId(Integer value);

    /**
     * Getter for <code>test1.user2.id</code>.
     */
    public Integer getId();

    /**
     * Setter for <code>test1.user2.address</code>.
     */
    public void setAddress(String value);

    /**
     * Getter for <code>test1.user2.address</code>.
     */
    public String getAddress();

    /**
     * Setter for <code>test1.user2.createtime</code>.
     */
    public void setCreatetime(Timestamp value);

    /**
     * Getter for <code>test1.user2.createtime</code>.
     */
    public Timestamp getCreatetime();

    /**
     * Setter for <code>test1.user2.isdeleted</code>.
     */
    public void setIsdeleted(String value);

    /**
     * Getter for <code>test1.user2.isdeleted</code>.
     */
    public String getIsdeleted();

    /**
     * Setter for <code>test1.user2.password</code>.
     */
    public void setPassword(String value);

    /**
     * Getter for <code>test1.user2.password</code>.
     */
    public String getPassword();

    /**
     * Setter for <code>test1.user2.sex</code>.
     */
    public void setSex(String value);

    /**
     * Getter for <code>test1.user2.sex</code>.
     */
    public String getSex();

    /**
     * Setter for <code>test1.user2.userfullname</code>.
     */
    public void setUserfullname(String value);

    /**
     * Getter for <code>test1.user2.userfullname</code>.
     */
    public String getUserfullname();

    /**
     * Setter for <code>test1.user2.username</code>.
     */
    public void setUsername(String value);

    /**
     * Getter for <code>test1.user2.username</code>.
     */
    public String getUsername();

    /**
     * Setter for <code>test1.user2.country_id</code>.
     */
    public void setCountryId(Integer value);

    /**
     * Getter for <code>test1.user2.country_id</code>.
     */
    public Integer getCountryId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IUser2
     */
    public void from(cn.qlq.jooq.tables.interfaces.IUser2 from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IUser2
     */
    public <E extends cn.qlq.jooq.tables.interfaces.IUser2> E into(E into);
}
