/*
 * This file is generated by jOOQ.
 */
package cn.qlq.jooq;


import cn.qlq.jooq.tables.COUNTRY;
import cn.qlq.jooq.tables.USER;
import cn.qlq.jooq.tables.USERCOUNTRY;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling indexes of tables of the <code>test1</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index COUNTRY_PRIMARY = Indexes0.COUNTRY_PRIMARY;
    public static final Index USER_PRIMARY = Indexes0.USER_PRIMARY;
    public static final Index USERCOUNTRY_PRIMARY = Indexes0.USERCOUNTRY_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index COUNTRY_PRIMARY = Internal.createIndex("PRIMARY", COUNTRY.COUNTRY, new OrderField[] { COUNTRY.COUNTRY.ID }, true);
        public static Index USER_PRIMARY = Internal.createIndex("PRIMARY", USER.USER, new OrderField[] { USER.USER.ID }, true);
        public static Index USERCOUNTRY_PRIMARY = Internal.createIndex("PRIMARY", USERCOUNTRY.USERCOUNTRY, new OrderField[] { USERCOUNTRY.USERCOUNTRY.USERID, USERCOUNTRY.USERCOUNTRY.COUNTRYID }, true);
    }
}
