/*
 * This file is generated by jOOQ.
 */
package cn.qlq.jooq;


import cn.qlq.jooq.tables.COUNTRY;
import cn.qlq.jooq.tables.USER;
import cn.qlq.jooq.tables.USERCOUNTRY;
import cn.qlq.jooq.tables.records.CountryRecord;
import cn.qlq.jooq.tables.records.UserRecord;
import cn.qlq.jooq.tables.records.UsercountryRecord;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>test1</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CountryRecord, Integer> IDENTITY_COUNTRY = Identities0.IDENTITY_COUNTRY;
    public static final Identity<UserRecord, Integer> IDENTITY_USER = Identities0.IDENTITY_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CountryRecord> KEY_COUNTRY_PRIMARY = UniqueKeys0.KEY_COUNTRY_PRIMARY;
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;
    public static final UniqueKey<UsercountryRecord> KEY_USERCOUNTRY_PRIMARY = UniqueKeys0.KEY_USERCOUNTRY_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<CountryRecord, Integer> IDENTITY_COUNTRY = Internal.createIdentity(COUNTRY.COUNTRY, COUNTRY.COUNTRY.ID);
        public static Identity<UserRecord, Integer> IDENTITY_USER = Internal.createIdentity(USER.USER, USER.USER.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<CountryRecord> KEY_COUNTRY_PRIMARY = Internal.createUniqueKey(COUNTRY.COUNTRY, "KEY_country_PRIMARY", COUNTRY.COUNTRY.ID);
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(USER.USER, "KEY_user_PRIMARY", USER.USER.ID);
        public static final UniqueKey<UsercountryRecord> KEY_USERCOUNTRY_PRIMARY = Internal.createUniqueKey(USERCOUNTRY.USERCOUNTRY, "KEY_usercountry_PRIMARY", USERCOUNTRY.USERCOUNTRY.USERID, USERCOUNTRY.USERCOUNTRY.COUNTRYID);
    }
}
