/*
 * This file is generated by jOOQ.
 */
package cn.qlq.jooq;


import cn.qlq.jooq.tables.USER;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in test1
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test1.country</code>.
     */
    public static final cn.qlq.jooq.tables.COUNTRY COUNTRY = cn.qlq.jooq.tables.COUNTRY.COUNTRY;

    /**
     * The table <code>test1.user</code>.
     */
    public static final USER USER = cn.qlq.jooq.tables.USER.USER;

    /**
     * The table <code>test1.usercountry</code>.
     */
    public static final cn.qlq.jooq.tables.USERCOUNTRY USERCOUNTRY = cn.qlq.jooq.tables.USERCOUNTRY.USERCOUNTRY;
}
