/*
 * This file is generated by jOOQ.
 */
package cn.qlq.jooq;


import cn.qlq.jooq.tables.COUNTRY;
import cn.qlq.jooq.tables.USER;
import cn.qlq.jooq.tables.USERCOUNTRY;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test1 extends SchemaImpl {

    private static final long serialVersionUID = 478874339;

    /**
     * The reference instance of <code>test1</code>
     */
    public static final Test1 TEST1 = new Test1();

    /**
     * The table <code>test1.country</code>.
     */
    public final COUNTRY COUNTRY = cn.qlq.jooq.tables.COUNTRY.COUNTRY;

    /**
     * The table <code>test1.user</code>.
     */
    public final USER USER = cn.qlq.jooq.tables.USER.USER;

    /**
     * The table <code>test1.usercountry</code>.
     */
    public final USERCOUNTRY USERCOUNTRY = cn.qlq.jooq.tables.USERCOUNTRY.USERCOUNTRY;

    /**
     * No further instances allowed
     */
    private Test1() {
        super("test1", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            COUNTRY.COUNTRY,
            USER.USER,
            USERCOUNTRY.USERCOUNTRY);
    }
}
