/*
 * This file is generated by jOOQ.
 */
package cn.qlq.jooq.tables;


import cn.qlq.jooq.Indexes;
import cn.qlq.jooq.Keys;
import cn.qlq.jooq.Test1;
import cn.qlq.jooq.tables.records.SystemShiroUserRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SYSTEM_SHIRO_USER extends TableImpl<SystemShiroUserRecord> {

    private static final long serialVersionUID = 1903493458;

    /**
     * The reference instance of <code>test1.system_shiro_user</code>
     */
    public static final SYSTEM_SHIRO_USER SYSTEM_SHIRO_USER = new SYSTEM_SHIRO_USER();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SystemShiroUserRecord> getRecordType() {
        return SystemShiroUserRecord.class;
    }

    /**
     * The column <code>test1.system_shiro_user.id</code>.
     */
    public final TableField<SystemShiroUserRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>test1.system_shiro_user.password</code>.
     */
    public final TableField<SystemShiroUserRecord, String> PASSWORD = createField(DSL.name("password"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>test1.system_shiro_user.username</code>.
     */
    public final TableField<SystemShiroUserRecord, String> USERNAME = createField(DSL.name("username"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>test1.system_shiro_user</code> table reference
     */
    public SYSTEM_SHIRO_USER() {
        this(DSL.name("system_shiro_user"), null);
    }

    /**
     * Create an aliased <code>test1.system_shiro_user</code> table reference
     */
    public SYSTEM_SHIRO_USER(String alias) {
        this(DSL.name(alias), SYSTEM_SHIRO_USER);
    }

    /**
     * Create an aliased <code>test1.system_shiro_user</code> table reference
     */
    public SYSTEM_SHIRO_USER(Name alias) {
        this(alias, SYSTEM_SHIRO_USER);
    }

    private SYSTEM_SHIRO_USER(Name alias, Table<SystemShiroUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private SYSTEM_SHIRO_USER(Name alias, Table<SystemShiroUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> SYSTEM_SHIRO_USER(Table<O> child, ForeignKey<O, SystemShiroUserRecord> key) {
        super(child, key, SYSTEM_SHIRO_USER);
    }

    @Override
    public Schema getSchema() {
        return Test1.TEST1;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SYSTEM_SHIRO_USER_PRIMARY);
    }

    @Override
    public UniqueKey<SystemShiroUserRecord> getPrimaryKey() {
        return Keys.KEY_SYSTEM_SHIRO_USER_PRIMARY;
    }

    @Override
    public List<UniqueKey<SystemShiroUserRecord>> getKeys() {
        return Arrays.<UniqueKey<SystemShiroUserRecord>>asList(Keys.KEY_SYSTEM_SHIRO_USER_PRIMARY);
    }

    @Override
    public SYSTEM_SHIRO_USER as(String alias) {
        return new SYSTEM_SHIRO_USER(DSL.name(alias), this);
    }

    @Override
    public SYSTEM_SHIRO_USER as(Name alias) {
        return new SYSTEM_SHIRO_USER(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SYSTEM_SHIRO_USER rename(String name) {
        return new SYSTEM_SHIRO_USER(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SYSTEM_SHIRO_USER rename(Name name) {
        return new SYSTEM_SHIRO_USER(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
