/*
 * This file is generated by jOOQ.
 */
package cn.qlq.jooq.tables;


import cn.qlq.jooq.Indexes;
import cn.qlq.jooq.Keys;
import cn.qlq.jooq.Test1;
import cn.qlq.jooq.tables.records.SystemShiroRolePermissionsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SYSTEM_SHIRO_ROLE_PERMISSIONS extends TableImpl<SystemShiroRolePermissionsRecord> {

    private static final long serialVersionUID = -813534814;

    /**
     * The reference instance of <code>test1.system_shiro_role_permissions</code>
     */
    public static final SYSTEM_SHIRO_ROLE_PERMISSIONS SYSTEM_SHIRO_ROLE_PERMISSIONS = new SYSTEM_SHIRO_ROLE_PERMISSIONS();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SystemShiroRolePermissionsRecord> getRecordType() {
        return SystemShiroRolePermissionsRecord.class;
    }

    /**
     * The column <code>test1.system_shiro_role_permissions.role_id</code>.
     */
    public final TableField<SystemShiroRolePermissionsRecord, Integer> ROLE_ID = createField(DSL.name("role_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>test1.system_shiro_role_permissions.permissions_id</code>.
     */
    public final TableField<SystemShiroRolePermissionsRecord, Integer> PERMISSIONS_ID = createField(DSL.name("permissions_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>test1.system_shiro_role_permissions</code> table reference
     */
    public SYSTEM_SHIRO_ROLE_PERMISSIONS() {
        this(DSL.name("system_shiro_role_permissions"), null);
    }

    /**
     * Create an aliased <code>test1.system_shiro_role_permissions</code> table reference
     */
    public SYSTEM_SHIRO_ROLE_PERMISSIONS(String alias) {
        this(DSL.name(alias), SYSTEM_SHIRO_ROLE_PERMISSIONS);
    }

    /**
     * Create an aliased <code>test1.system_shiro_role_permissions</code> table reference
     */
    public SYSTEM_SHIRO_ROLE_PERMISSIONS(Name alias) {
        this(alias, SYSTEM_SHIRO_ROLE_PERMISSIONS);
    }

    private SYSTEM_SHIRO_ROLE_PERMISSIONS(Name alias, Table<SystemShiroRolePermissionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private SYSTEM_SHIRO_ROLE_PERMISSIONS(Name alias, Table<SystemShiroRolePermissionsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> SYSTEM_SHIRO_ROLE_PERMISSIONS(Table<O> child, ForeignKey<O, SystemShiroRolePermissionsRecord> key) {
        super(child, key, SYSTEM_SHIRO_ROLE_PERMISSIONS);
    }

    @Override
    public Schema getSchema() {
        return Test1.TEST1;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SYSTEM_SHIRO_ROLE_PERMISSIONS_FKID5G3KH3JHOJ05A1JBT3GWXE9, Indexes.SYSTEM_SHIRO_ROLE_PERMISSIONS_UK_9BGRR9Y35K9DEH6OS7FQ2HXJC);
    }

    @Override
    public List<UniqueKey<SystemShiroRolePermissionsRecord>> getKeys() {
        return Arrays.<UniqueKey<SystemShiroRolePermissionsRecord>>asList(Keys.KEY_SYSTEM_SHIRO_ROLE_PERMISSIONS_UK_9BGRR9Y35K9DEH6OS7FQ2HXJC);
    }

    @Override
    public SYSTEM_SHIRO_ROLE_PERMISSIONS as(String alias) {
        return new SYSTEM_SHIRO_ROLE_PERMISSIONS(DSL.name(alias), this);
    }

    @Override
    public SYSTEM_SHIRO_ROLE_PERMISSIONS as(Name alias) {
        return new SYSTEM_SHIRO_ROLE_PERMISSIONS(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SYSTEM_SHIRO_ROLE_PERMISSIONS rename(String name) {
        return new SYSTEM_SHIRO_ROLE_PERMISSIONS(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SYSTEM_SHIRO_ROLE_PERMISSIONS rename(Name name) {
        return new SYSTEM_SHIRO_ROLE_PERMISSIONS(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
