/*
 * This file is generated by jOOQ.
 */
package cn.qlq.jooq.tables;


import cn.qlq.jooq.Indexes;
import cn.qlq.jooq.Keys;
import cn.qlq.jooq.Test1;
import cn.qlq.jooq.tables.records.SystemShiroUserRolesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SYSTEM_SHIRO_USER_ROLES extends TableImpl<SystemShiroUserRolesRecord> {

    private static final long serialVersionUID = -1046868914;

    /**
     * The reference instance of <code>test1.system_shiro_user_roles</code>
     */
    public static final SYSTEM_SHIRO_USER_ROLES SYSTEM_SHIRO_USER_ROLES = new SYSTEM_SHIRO_USER_ROLES();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SystemShiroUserRolesRecord> getRecordType() {
        return SystemShiroUserRolesRecord.class;
    }

    /**
     * The column <code>test1.system_shiro_user_roles.shiro_user_id</code>.
     */
    public final TableField<SystemShiroUserRolesRecord, Integer> SHIRO_USER_ID = createField(DSL.name("shiro_user_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>test1.system_shiro_user_roles.roles_id</code>.
     */
    public final TableField<SystemShiroUserRolesRecord, Integer> ROLES_ID = createField(DSL.name("roles_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>test1.system_shiro_user_roles</code> table reference
     */
    public SYSTEM_SHIRO_USER_ROLES() {
        this(DSL.name("system_shiro_user_roles"), null);
    }

    /**
     * Create an aliased <code>test1.system_shiro_user_roles</code> table reference
     */
    public SYSTEM_SHIRO_USER_ROLES(String alias) {
        this(DSL.name(alias), SYSTEM_SHIRO_USER_ROLES);
    }

    /**
     * Create an aliased <code>test1.system_shiro_user_roles</code> table reference
     */
    public SYSTEM_SHIRO_USER_ROLES(Name alias) {
        this(alias, SYSTEM_SHIRO_USER_ROLES);
    }

    private SYSTEM_SHIRO_USER_ROLES(Name alias, Table<SystemShiroUserRolesRecord> aliased) {
        this(alias, aliased, null);
    }

    private SYSTEM_SHIRO_USER_ROLES(Name alias, Table<SystemShiroUserRolesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> SYSTEM_SHIRO_USER_ROLES(Table<O> child, ForeignKey<O, SystemShiroUserRolesRecord> key) {
        super(child, key, SYSTEM_SHIRO_USER_ROLES);
    }

    @Override
    public Schema getSchema() {
        return Test1.TEST1;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SYSTEM_SHIRO_USER_ROLES_FKJ4GCMLP5WM0FAPX9VUUOIS1MF, Indexes.SYSTEM_SHIRO_USER_ROLES_UK_I8LLCNOHDPE9U5XFNBA0G4JQY);
    }

    @Override
    public List<UniqueKey<SystemShiroUserRolesRecord>> getKeys() {
        return Arrays.<UniqueKey<SystemShiroUserRolesRecord>>asList(Keys.KEY_SYSTEM_SHIRO_USER_ROLES_UK_I8LLCNOHDPE9U5XFNBA0G4JQY);
    }

    @Override
    public SYSTEM_SHIRO_USER_ROLES as(String alias) {
        return new SYSTEM_SHIRO_USER_ROLES(DSL.name(alias), this);
    }

    @Override
    public SYSTEM_SHIRO_USER_ROLES as(Name alias) {
        return new SYSTEM_SHIRO_USER_ROLES(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SYSTEM_SHIRO_USER_ROLES rename(String name) {
        return new SYSTEM_SHIRO_USER_ROLES(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SYSTEM_SHIRO_USER_ROLES rename(Name name) {
        return new SYSTEM_SHIRO_USER_ROLES(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
