/*
 * This file is generated by jOOQ.
 */
package cn.qlq.jooq.tables.pojos;


import cn.qlq.jooq.tables.interfaces.ICountry;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Country implements ICountry {

    private static final long serialVersionUID = 1559699795;

    private Integer id;
    private String  countryname;

    public Country() {}

    public Country(ICountry value) {
        this.id = value.getId();
        this.countryname = value.getCountryname();
    }

    public Country(
        Integer id,
        String  countryname
    ) {
        this.id = id;
        this.countryname = countryname;
    }

    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public String getCountryname() {
        return this.countryname;
    }

    @Override
    public void setCountryname(String countryname) {
        this.countryname = countryname;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Country (");

        sb.append(id);
        sb.append(", ").append(countryname);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ICountry from) {
        setId(from.getId());
        setCountryname(from.getCountryname());
    }

    @Override
    public <E extends ICountry> E into(E into) {
        into.from(this);
        return into;
    }
}
