/*
 * This file is generated by jOOQ.
 */
package cn.qlq.jooq.tables.pojos;


import cn.qlq.jooq.tables.interfaces.IHibernateSequence;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HibernateSequence implements IHibernateSequence {

    private static final long serialVersionUID = -1238617593;

    private Long nextVal;

    public HibernateSequence() {}

    public HibernateSequence(IHibernateSequence value) {
        this.nextVal = value.getNextVal();
    }

    public HibernateSequence(
        Long nextVal
    ) {
        this.nextVal = nextVal;
    }

    @Override
    public Long getNextVal() {
        return this.nextVal;
    }

    @Override
    public void setNextVal(Long nextVal) {
        this.nextVal = nextVal;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("HibernateSequence (");

        sb.append(nextVal);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IHibernateSequence from) {
        setNextVal(from.getNextVal());
    }

    @Override
    public <E extends IHibernateSequence> E into(E into) {
        into.from(this);
        return into;
    }
}
