/*
 * This file is generated by jOOQ.
 */
package cn.qlq.jooq.tables.pojos;


import cn.qlq.jooq.tables.interfaces.ISystemShiroUser;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemShiroUser implements ISystemShiroUser {

    private static final long serialVersionUID = -718310677;

    private Integer id;
    private String  password;
    private String  username;

    public SystemShiroUser() {}

    public SystemShiroUser(ISystemShiroUser value) {
        this.id = value.getId();
        this.password = value.getPassword();
        this.username = value.getUsername();
    }

    public SystemShiroUser(
        Integer id,
        String  password,
        String  username
    ) {
        this.id = id;
        this.password = password;
        this.username = username;
    }

    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public String getPassword() {
        return this.password;
    }

    @Override
    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String getUsername() {
        return this.username;
    }

    @Override
    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SystemShiroUser (");

        sb.append(id);
        sb.append(", ").append(password);
        sb.append(", ").append(username);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ISystemShiroUser from) {
        setId(from.getId());
        setPassword(from.getPassword());
        setUsername(from.getUsername());
    }

    @Override
    public <E extends ISystemShiroUser> E into(E into) {
        into.from(this);
        return into;
    }
}
