/*
 * This file is generated by jOOQ.
 */
package cn.qlq.jooq.tables.pojos;


import cn.qlq.jooq.tables.interfaces.ISystemShiroRolePermissions;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemShiroRolePermissions implements ISystemShiroRolePermissions {

    private static final long serialVersionUID = 1304056937;

    private Integer roleId;
    private Integer permissionsId;

    public SystemShiroRolePermissions() {}

    public SystemShiroRolePermissions(ISystemShiroRolePermissions value) {
        this.roleId = value.getRoleId();
        this.permissionsId = value.getPermissionsId();
    }

    public SystemShiroRolePermissions(
        Integer roleId,
        Integer permissionsId
    ) {
        this.roleId = roleId;
        this.permissionsId = permissionsId;
    }

    @Override
    public Integer getRoleId() {
        return this.roleId;
    }

    @Override
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    @Override
    public Integer getPermissionsId() {
        return this.permissionsId;
    }

    @Override
    public void setPermissionsId(Integer permissionsId) {
        this.permissionsId = permissionsId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SystemShiroRolePermissions (");

        sb.append(roleId);
        sb.append(", ").append(permissionsId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ISystemShiroRolePermissions from) {
        setRoleId(from.getRoleId());
        setPermissionsId(from.getPermissionsId());
    }

    @Override
    public <E extends ISystemShiroRolePermissions> E into(E into) {
        into.from(this);
        return into;
    }
}
