/*
 * This file is generated by jOOQ.
 */
package cn.qlq.jooq.tables.pojos;


import cn.qlq.jooq.tables.interfaces.ISystemShiroPermission;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemShiroPermission implements ISystemShiroPermission {

    private static final long serialVersionUID = -753248372;

    private Integer id;
    private String  description;
    private String  name;
    private String  url;

    public SystemShiroPermission() {}

    public SystemShiroPermission(ISystemShiroPermission value) {
        this.id = value.getId();
        this.description = value.getDescription();
        this.name = value.getName();
        this.url = value.getUrl();
    }

    public SystemShiroPermission(
        Integer id,
        String  description,
        String  name,
        String  url
    ) {
        this.id = id;
        this.description = description;
        this.name = name;
        this.url = url;
    }

    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public String getDescription() {
        return this.description;
    }

    @Override
    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String getUrl() {
        return this.url;
    }

    @Override
    public void setUrl(String url) {
        this.url = url;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SystemShiroPermission (");

        sb.append(id);
        sb.append(", ").append(description);
        sb.append(", ").append(name);
        sb.append(", ").append(url);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ISystemShiroPermission from) {
        setId(from.getId());
        setDescription(from.getDescription());
        setName(from.getName());
        setUrl(from.getUrl());
    }

    @Override
    public <E extends ISystemShiroPermission> E into(E into) {
        into.from(this);
        return into;
    }
}
