/*
 * This file is generated by jOOQ.
 */
package cn.qlq.jooq.tables.pojos;


import cn.qlq.jooq.tables.interfaces.IUser2;

import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User2 implements IUser2 {

    private static final long serialVersionUID = -6208889;

    private Integer   id;
    private String    address;
    private Timestamp createtime;
    private String    isdeleted;
    private String    password;
    private String    sex;
    private String    userfullname;
    private String    username;
    private Integer   countryId;

    public User2() {}

    public User2(IUser2 value) {
        this.id = value.getId();
        this.address = value.getAddress();
        this.createtime = value.getCreatetime();
        this.isdeleted = value.getIsdeleted();
        this.password = value.getPassword();
        this.sex = value.getSex();
        this.userfullname = value.getUserfullname();
        this.username = value.getUsername();
        this.countryId = value.getCountryId();
    }

    public User2(
        Integer   id,
        String    address,
        Timestamp createtime,
        String    isdeleted,
        String    password,
        String    sex,
        String    userfullname,
        String    username,
        Integer   countryId
    ) {
        this.id = id;
        this.address = address;
        this.createtime = createtime;
        this.isdeleted = isdeleted;
        this.password = password;
        this.sex = sex;
        this.userfullname = userfullname;
        this.username = username;
        this.countryId = countryId;
    }

    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public String getAddress() {
        return this.address;
    }

    @Override
    public void setAddress(String address) {
        this.address = address;
    }

    @Override
    public Timestamp getCreatetime() {
        return this.createtime;
    }

    @Override
    public void setCreatetime(Timestamp createtime) {
        this.createtime = createtime;
    }

    @Override
    public String getIsdeleted() {
        return this.isdeleted;
    }

    @Override
    public void setIsdeleted(String isdeleted) {
        this.isdeleted = isdeleted;
    }

    @Override
    public String getPassword() {
        return this.password;
    }

    @Override
    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String getSex() {
        return this.sex;
    }

    @Override
    public void setSex(String sex) {
        this.sex = sex;
    }

    @Override
    public String getUserfullname() {
        return this.userfullname;
    }

    @Override
    public void setUserfullname(String userfullname) {
        this.userfullname = userfullname;
    }

    @Override
    public String getUsername() {
        return this.username;
    }

    @Override
    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public Integer getCountryId() {
        return this.countryId;
    }

    @Override
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User2 (");

        sb.append(id);
        sb.append(", ").append(address);
        sb.append(", ").append(createtime);
        sb.append(", ").append(isdeleted);
        sb.append(", ").append(password);
        sb.append(", ").append(sex);
        sb.append(", ").append(userfullname);
        sb.append(", ").append(username);
        sb.append(", ").append(countryId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUser2 from) {
        setId(from.getId());
        setAddress(from.getAddress());
        setCreatetime(from.getCreatetime());
        setIsdeleted(from.getIsdeleted());
        setPassword(from.getPassword());
        setSex(from.getSex());
        setUserfullname(from.getUserfullname());
        setUsername(from.getUsername());
        setCountryId(from.getCountryId());
    }

    @Override
    public <E extends IUser2> E into(E into) {
        into.from(this);
        return into;
    }
}
