/*
 * This file is generated by jOOQ.
 */
package cn.qlq.jooq.tables.records;


import cn.qlq.jooq.tables.FLYWAY_SCHEMA_HISTORY;
import cn.qlq.jooq.tables.interfaces.IFlywaySchemaHistory;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FlywaySchemaHistoryRecord extends UpdatableRecordImpl<FlywaySchemaHistoryRecord> implements Record10<Integer, String, String, String, String, Integer, String, Timestamp, Integer, Byte>, IFlywaySchemaHistory {

    private static final long serialVersionUID = -533538889;

    /**
     * Setter for <code>test1.flyway_schema_history.installed_rank</code>.
     */
    @Override
    public void setInstalledRank(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>test1.flyway_schema_history.installed_rank</code>.
     */
    @Override
    public Integer getInstalledRank() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>test1.flyway_schema_history.version</code>.
     */
    @Override
    public void setVersion(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>test1.flyway_schema_history.version</code>.
     */
    @Override
    public String getVersion() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test1.flyway_schema_history.description</code>.
     */
    @Override
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>test1.flyway_schema_history.description</code>.
     */
    @Override
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>test1.flyway_schema_history.type</code>.
     */
    @Override
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>test1.flyway_schema_history.type</code>.
     */
    @Override
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>test1.flyway_schema_history.script</code>.
     */
    @Override
    public void setScript(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>test1.flyway_schema_history.script</code>.
     */
    @Override
    public String getScript() {
        return (String) get(4);
    }

    /**
     * Setter for <code>test1.flyway_schema_history.checksum</code>.
     */
    @Override
    public void setChecksum(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>test1.flyway_schema_history.checksum</code>.
     */
    @Override
    public Integer getChecksum() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>test1.flyway_schema_history.installed_by</code>.
     */
    @Override
    public void setInstalledBy(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>test1.flyway_schema_history.installed_by</code>.
     */
    @Override
    public String getInstalledBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>test1.flyway_schema_history.installed_on</code>.
     */
    @Override
    public void setInstalledOn(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>test1.flyway_schema_history.installed_on</code>.
     */
    @Override
    public Timestamp getInstalledOn() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>test1.flyway_schema_history.execution_time</code>.
     */
    @Override
    public void setExecutionTime(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>test1.flyway_schema_history.execution_time</code>.
     */
    @Override
    public Integer getExecutionTime() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>test1.flyway_schema_history.success</code>.
     */
    @Override
    public void setSuccess(Byte value) {
        set(9, value);
    }

    /**
     * Getter for <code>test1.flyway_schema_history.success</code>.
     */
    @Override
    public Byte getSuccess() {
        return (Byte) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, String, String, String, Integer, String, Timestamp, Integer, Byte> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, String, String, String, String, Integer, String, Timestamp, Integer, Byte> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return FLYWAY_SCHEMA_HISTORY.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK;
    }

    @Override
    public Field<String> field2() {
        return FLYWAY_SCHEMA_HISTORY.FLYWAY_SCHEMA_HISTORY.VERSION;
    }

    @Override
    public Field<String> field3() {
        return FLYWAY_SCHEMA_HISTORY.FLYWAY_SCHEMA_HISTORY.DESCRIPTION;
    }

    @Override
    public Field<String> field4() {
        return FLYWAY_SCHEMA_HISTORY.FLYWAY_SCHEMA_HISTORY.TYPE;
    }

    @Override
    public Field<String> field5() {
        return FLYWAY_SCHEMA_HISTORY.FLYWAY_SCHEMA_HISTORY.SCRIPT;
    }

    @Override
    public Field<Integer> field6() {
        return FLYWAY_SCHEMA_HISTORY.FLYWAY_SCHEMA_HISTORY.CHECKSUM;
    }

    @Override
    public Field<String> field7() {
        return FLYWAY_SCHEMA_HISTORY.FLYWAY_SCHEMA_HISTORY.INSTALLED_BY;
    }

    @Override
    public Field<Timestamp> field8() {
        return FLYWAY_SCHEMA_HISTORY.FLYWAY_SCHEMA_HISTORY.INSTALLED_ON;
    }

    @Override
    public Field<Integer> field9() {
        return FLYWAY_SCHEMA_HISTORY.FLYWAY_SCHEMA_HISTORY.EXECUTION_TIME;
    }

    @Override
    public Field<Byte> field10() {
        return FLYWAY_SCHEMA_HISTORY.FLYWAY_SCHEMA_HISTORY.SUCCESS;
    }

    @Override
    public Integer component1() {
        return getInstalledRank();
    }

    @Override
    public String component2() {
        return getVersion();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public String component4() {
        return getType();
    }

    @Override
    public String component5() {
        return getScript();
    }

    @Override
    public Integer component6() {
        return getChecksum();
    }

    @Override
    public String component7() {
        return getInstalledBy();
    }

    @Override
    public Timestamp component8() {
        return getInstalledOn();
    }

    @Override
    public Integer component9() {
        return getExecutionTime();
    }

    @Override
    public Byte component10() {
        return getSuccess();
    }

    @Override
    public Integer value1() {
        return getInstalledRank();
    }

    @Override
    public String value2() {
        return getVersion();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public String value4() {
        return getType();
    }

    @Override
    public String value5() {
        return getScript();
    }

    @Override
    public Integer value6() {
        return getChecksum();
    }

    @Override
    public String value7() {
        return getInstalledBy();
    }

    @Override
    public Timestamp value8() {
        return getInstalledOn();
    }

    @Override
    public Integer value9() {
        return getExecutionTime();
    }

    @Override
    public Byte value10() {
        return getSuccess();
    }

    @Override
    public FlywaySchemaHistoryRecord value1(Integer value) {
        setInstalledRank(value);
        return this;
    }

    @Override
    public FlywaySchemaHistoryRecord value2(String value) {
        setVersion(value);
        return this;
    }

    @Override
    public FlywaySchemaHistoryRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public FlywaySchemaHistoryRecord value4(String value) {
        setType(value);
        return this;
    }

    @Override
    public FlywaySchemaHistoryRecord value5(String value) {
        setScript(value);
        return this;
    }

    @Override
    public FlywaySchemaHistoryRecord value6(Integer value) {
        setChecksum(value);
        return this;
    }

    @Override
    public FlywaySchemaHistoryRecord value7(String value) {
        setInstalledBy(value);
        return this;
    }

    @Override
    public FlywaySchemaHistoryRecord value8(Timestamp value) {
        setInstalledOn(value);
        return this;
    }

    @Override
    public FlywaySchemaHistoryRecord value9(Integer value) {
        setExecutionTime(value);
        return this;
    }

    @Override
    public FlywaySchemaHistoryRecord value10(Byte value) {
        setSuccess(value);
        return this;
    }

    @Override
    public FlywaySchemaHistoryRecord values(Integer value1, String value2, String value3, String value4, String value5, Integer value6, String value7, Timestamp value8, Integer value9, Byte value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IFlywaySchemaHistory from) {
        setInstalledRank(from.getInstalledRank());
        setVersion(from.getVersion());
        setDescription(from.getDescription());
        setType(from.getType());
        setScript(from.getScript());
        setChecksum(from.getChecksum());
        setInstalledBy(from.getInstalledBy());
        setInstalledOn(from.getInstalledOn());
        setExecutionTime(from.getExecutionTime());
        setSuccess(from.getSuccess());
    }

    @Override
    public <E extends IFlywaySchemaHistory> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FlywaySchemaHistoryRecord
     */
    public FlywaySchemaHistoryRecord() {
        super(FLYWAY_SCHEMA_HISTORY.FLYWAY_SCHEMA_HISTORY);
    }

    /**
     * Create a detached, initialised FlywaySchemaHistoryRecord
     */
    public FlywaySchemaHistoryRecord(Integer installedRank, String version, String description, String type, String script, Integer checksum, String installedBy, Timestamp installedOn, Integer executionTime, Byte success) {
        super(FLYWAY_SCHEMA_HISTORY.FLYWAY_SCHEMA_HISTORY);

        set(0, installedRank);
        set(1, version);
        set(2, description);
        set(3, type);
        set(4, script);
        set(5, checksum);
        set(6, installedBy);
        set(7, installedOn);
        set(8, executionTime);
        set(9, success);
    }
}
