/*
 * This file is generated by jOOQ.
 */
package cn.qlq.jooq.tables.records;


import cn.qlq.jooq.tables.HIBERNATE_SEQUENCE;
import cn.qlq.jooq.tables.interfaces.IHibernateSequence;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HibernateSequenceRecord extends TableRecordImpl<HibernateSequenceRecord> implements Record1<Long>, IHibernateSequence {

    private static final long serialVersionUID = 457685403;

    /**
     * Setter for <code>test1.hibernate_sequence.next_val</code>.
     */
    @Override
    public void setNextVal(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>test1.hibernate_sequence.next_val</code>.
     */
    @Override
    public Long getNextVal() {
        return (Long) get(0);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<Long> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<Long> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return HIBERNATE_SEQUENCE.HIBERNATE_SEQUENCE.NEXT_VAL;
    }

    @Override
    public Long component1() {
        return getNextVal();
    }

    @Override
    public Long value1() {
        return getNextVal();
    }

    @Override
    public HibernateSequenceRecord value1(Long value) {
        setNextVal(value);
        return this;
    }

    @Override
    public HibernateSequenceRecord values(Long value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IHibernateSequence from) {
        setNextVal(from.getNextVal());
    }

    @Override
    public <E extends IHibernateSequence> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HibernateSequenceRecord
     */
    public HibernateSequenceRecord() {
        super(HIBERNATE_SEQUENCE.HIBERNATE_SEQUENCE);
    }

    /**
     * Create a detached, initialised HibernateSequenceRecord
     */
    public HibernateSequenceRecord(Long nextVal) {
        super(HIBERNATE_SEQUENCE.HIBERNATE_SEQUENCE);

        set(0, nextVal);
    }
}
