/*
 * This file is generated by jOOQ.
 */
package cn.qlq.jooq.tables.records;


import cn.qlq.jooq.tables.MP_USER;
import cn.qlq.jooq.tables.interfaces.IMpUser;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MpUserRecord extends UpdatableRecordImpl<MpUserRecord> implements Record6<Long, Integer, Integer, String, String, String>, IMpUser {

    private static final long serialVersionUID = -1876891678;

    /**
     * Setter for <code>test1.mp_user.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>test1.mp_user.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>test1.mp_user.age</code>.
     */
    @Override
    public void setAge(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>test1.mp_user.age</code>.
     */
    @Override
    public Integer getAge() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>test1.mp_user.deleted</code>.
     */
    @Override
    public void setDeleted(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>test1.mp_user.deleted</code>.
     */
    @Override
    public Integer getDeleted() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>test1.mp_user.email</code>.
     */
    @Override
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>test1.mp_user.email</code>.
     */
    @Override
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>test1.mp_user.name</code>.
     */
    @Override
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>test1.mp_user.name</code>.
     */
    @Override
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>test1.mp_user.unique_code</code>.
     */
    @Override
    public void setUniqueCode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>test1.mp_user.unique_code</code>.
     */
    @Override
    public String getUniqueCode() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Integer, Integer, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Integer, Integer, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MP_USER.MP_USER.ID;
    }

    @Override
    public Field<Integer> field2() {
        return MP_USER.MP_USER.AGE;
    }

    @Override
    public Field<Integer> field3() {
        return MP_USER.MP_USER.DELETED;
    }

    @Override
    public Field<String> field4() {
        return MP_USER.MP_USER.EMAIL;
    }

    @Override
    public Field<String> field5() {
        return MP_USER.MP_USER.NAME;
    }

    @Override
    public Field<String> field6() {
        return MP_USER.MP_USER.UNIQUE_CODE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getAge();
    }

    @Override
    public Integer component3() {
        return getDeleted();
    }

    @Override
    public String component4() {
        return getEmail();
    }

    @Override
    public String component5() {
        return getName();
    }

    @Override
    public String component6() {
        return getUniqueCode();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getAge();
    }

    @Override
    public Integer value3() {
        return getDeleted();
    }

    @Override
    public String value4() {
        return getEmail();
    }

    @Override
    public String value5() {
        return getName();
    }

    @Override
    public String value6() {
        return getUniqueCode();
    }

    @Override
    public MpUserRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MpUserRecord value2(Integer value) {
        setAge(value);
        return this;
    }

    @Override
    public MpUserRecord value3(Integer value) {
        setDeleted(value);
        return this;
    }

    @Override
    public MpUserRecord value4(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public MpUserRecord value5(String value) {
        setName(value);
        return this;
    }

    @Override
    public MpUserRecord value6(String value) {
        setUniqueCode(value);
        return this;
    }

    @Override
    public MpUserRecord values(Long value1, Integer value2, Integer value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IMpUser from) {
        setId(from.getId());
        setAge(from.getAge());
        setDeleted(from.getDeleted());
        setEmail(from.getEmail());
        setName(from.getName());
        setUniqueCode(from.getUniqueCode());
    }

    @Override
    public <E extends IMpUser> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MpUserRecord
     */
    public MpUserRecord() {
        super(MP_USER.MP_USER);
    }

    /**
     * Create a detached, initialised MpUserRecord
     */
    public MpUserRecord(Long id, Integer age, Integer deleted, String email, String name, String uniqueCode) {
        super(MP_USER.MP_USER);

        set(0, id);
        set(1, age);
        set(2, deleted);
        set(3, email);
        set(4, name);
        set(5, uniqueCode);
    }
}
