/*
 * This file is generated by jOOQ.
 */
package cn.qlq.jooq.tables.records;


import cn.qlq.jooq.tables.SYSTEM_SHIRO_USER_ROLES;
import cn.qlq.jooq.tables.interfaces.ISystemShiroUserRoles;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemShiroUserRolesRecord extends TableRecordImpl<SystemShiroUserRolesRecord> implements Record2<Integer, Integer>, ISystemShiroUserRoles {

    private static final long serialVersionUID = -472561670;

    /**
     * Setter for <code>test1.system_shiro_user_roles.shiro_user_id</code>.
     */
    @Override
    public void setShiroUserId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>test1.system_shiro_user_roles.shiro_user_id</code>.
     */
    @Override
    public Integer getShiroUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>test1.system_shiro_user_roles.roles_id</code>.
     */
    @Override
    public void setRolesId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>test1.system_shiro_user_roles.roles_id</code>.
     */
    @Override
    public Integer getRolesId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return SYSTEM_SHIRO_USER_ROLES.SYSTEM_SHIRO_USER_ROLES.SHIRO_USER_ID;
    }

    @Override
    public Field<Integer> field2() {
        return SYSTEM_SHIRO_USER_ROLES.SYSTEM_SHIRO_USER_ROLES.ROLES_ID;
    }

    @Override
    public Integer component1() {
        return getShiroUserId();
    }

    @Override
    public Integer component2() {
        return getRolesId();
    }

    @Override
    public Integer value1() {
        return getShiroUserId();
    }

    @Override
    public Integer value2() {
        return getRolesId();
    }

    @Override
    public SystemShiroUserRolesRecord value1(Integer value) {
        setShiroUserId(value);
        return this;
    }

    @Override
    public SystemShiroUserRolesRecord value2(Integer value) {
        setRolesId(value);
        return this;
    }

    @Override
    public SystemShiroUserRolesRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ISystemShiroUserRoles from) {
        setShiroUserId(from.getShiroUserId());
        setRolesId(from.getRolesId());
    }

    @Override
    public <E extends ISystemShiroUserRoles> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SystemShiroUserRolesRecord
     */
    public SystemShiroUserRolesRecord() {
        super(SYSTEM_SHIRO_USER_ROLES.SYSTEM_SHIRO_USER_ROLES);
    }

    /**
     * Create a detached, initialised SystemShiroUserRolesRecord
     */
    public SystemShiroUserRolesRecord(Integer shiroUserId, Integer rolesId) {
        super(SYSTEM_SHIRO_USER_ROLES.SYSTEM_SHIRO_USER_ROLES);

        set(0, shiroUserId);
        set(1, rolesId);
    }
}
