/*
 * This file is generated by jOOQ.
 */
package cn.qlq.jooq.tables.records;


import cn.qlq.jooq.tables.SYSTEM_SHIRO_ROLE;
import cn.qlq.jooq.tables.interfaces.ISystemShiroRole;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemShiroRoleRecord extends UpdatableRecordImpl<SystemShiroRoleRecord> implements Record3<Integer, String, String>, ISystemShiroRole {

    private static final long serialVersionUID = -315874088;

    /**
     * Setter for <code>test1.system_shiro_role.id</code>.
     */
    @Override
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>test1.system_shiro_role.id</code>.
     */
    @Override
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>test1.system_shiro_role.description</code>.
     */
    @Override
    public void setDescription(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>test1.system_shiro_role.description</code>.
     */
    @Override
    public String getDescription() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test1.system_shiro_role.name</code>.
     */
    @Override
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>test1.system_shiro_role.name</code>.
     */
    @Override
    public String getName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return SYSTEM_SHIRO_ROLE.SYSTEM_SHIRO_ROLE.ID;
    }

    @Override
    public Field<String> field2() {
        return SYSTEM_SHIRO_ROLE.SYSTEM_SHIRO_ROLE.DESCRIPTION;
    }

    @Override
    public Field<String> field3() {
        return SYSTEM_SHIRO_ROLE.SYSTEM_SHIRO_ROLE.NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getDescription();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getDescription();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public SystemShiroRoleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SystemShiroRoleRecord value2(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public SystemShiroRoleRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public SystemShiroRoleRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ISystemShiroRole from) {
        setId(from.getId());
        setDescription(from.getDescription());
        setName(from.getName());
    }

    @Override
    public <E extends ISystemShiroRole> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SystemShiroRoleRecord
     */
    public SystemShiroRoleRecord() {
        super(SYSTEM_SHIRO_ROLE.SYSTEM_SHIRO_ROLE);
    }

    /**
     * Create a detached, initialised SystemShiroRoleRecord
     */
    public SystemShiroRoleRecord(Integer id, String description, String name) {
        super(SYSTEM_SHIRO_ROLE.SYSTEM_SHIRO_ROLE);

        set(0, id);
        set(1, description);
        set(2, name);
    }
}
