/*
 * This file is generated by jOOQ.
 */
package cn.qlq.jooq.tables.records;


import cn.qlq.jooq.tables.SYSTEM_SHIRO_PERMISSION;
import cn.qlq.jooq.tables.interfaces.ISystemShiroPermission;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemShiroPermissionRecord extends UpdatableRecordImpl<SystemShiroPermissionRecord> implements Record4<Integer, String, String, String>, ISystemShiroPermission {

    private static final long serialVersionUID = -1021975690;

    /**
     * Setter for <code>test1.system_shiro_permission.id</code>.
     */
    @Override
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>test1.system_shiro_permission.id</code>.
     */
    @Override
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>test1.system_shiro_permission.description</code>.
     */
    @Override
    public void setDescription(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>test1.system_shiro_permission.description</code>.
     */
    @Override
    public String getDescription() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test1.system_shiro_permission.name</code>.
     */
    @Override
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>test1.system_shiro_permission.name</code>.
     */
    @Override
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>test1.system_shiro_permission.url</code>.
     */
    @Override
    public void setUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>test1.system_shiro_permission.url</code>.
     */
    @Override
    public String getUrl() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return SYSTEM_SHIRO_PERMISSION.SYSTEM_SHIRO_PERMISSION.ID;
    }

    @Override
    public Field<String> field2() {
        return SYSTEM_SHIRO_PERMISSION.SYSTEM_SHIRO_PERMISSION.DESCRIPTION;
    }

    @Override
    public Field<String> field3() {
        return SYSTEM_SHIRO_PERMISSION.SYSTEM_SHIRO_PERMISSION.NAME;
    }

    @Override
    public Field<String> field4() {
        return SYSTEM_SHIRO_PERMISSION.SYSTEM_SHIRO_PERMISSION.URL;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getDescription();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getUrl();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getDescription();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getUrl();
    }

    @Override
    public SystemShiroPermissionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SystemShiroPermissionRecord value2(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public SystemShiroPermissionRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public SystemShiroPermissionRecord value4(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public SystemShiroPermissionRecord values(Integer value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ISystemShiroPermission from) {
        setId(from.getId());
        setDescription(from.getDescription());
        setName(from.getName());
        setUrl(from.getUrl());
    }

    @Override
    public <E extends ISystemShiroPermission> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SystemShiroPermissionRecord
     */
    public SystemShiroPermissionRecord() {
        super(SYSTEM_SHIRO_PERMISSION.SYSTEM_SHIRO_PERMISSION);
    }

    /**
     * Create a detached, initialised SystemShiroPermissionRecord
     */
    public SystemShiroPermissionRecord(Integer id, String description, String name, String url) {
        super(SYSTEM_SHIRO_PERMISSION.SYSTEM_SHIRO_PERMISSION);

        set(0, id);
        set(1, description);
        set(2, name);
        set(3, url);
    }
}
