/*
 * This file is generated by jOOQ.
 */
package cn.qlq.jooq.tables.records;


import cn.qlq.jooq.tables.USERCOUNTRY;
import cn.qlq.jooq.tables.interfaces.IUsercountry;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsercountryRecord extends UpdatableRecordImpl<UsercountryRecord> implements Record2<Integer, Integer>, IUsercountry {

    private static final long serialVersionUID = 422153851;

    /**
     * Setter for <code>test1.usercountry.userid</code>.
     */
    @Override
    public void setUserid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>test1.usercountry.userid</code>.
     */
    @Override
    public Integer getUserid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>test1.usercountry.countryid</code>.
     */
    @Override
    public void setCountryid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>test1.usercountry.countryid</code>.
     */
    @Override
    public Integer getCountryid() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return USERCOUNTRY.USERCOUNTRY.USERID;
    }

    @Override
    public Field<Integer> field2() {
        return USERCOUNTRY.USERCOUNTRY.COUNTRYID;
    }

    @Override
    public Integer component1() {
        return getUserid();
    }

    @Override
    public Integer component2() {
        return getCountryid();
    }

    @Override
    public Integer value1() {
        return getUserid();
    }

    @Override
    public Integer value2() {
        return getCountryid();
    }

    @Override
    public UsercountryRecord value1(Integer value) {
        setUserid(value);
        return this;
    }

    @Override
    public UsercountryRecord value2(Integer value) {
        setCountryid(value);
        return this;
    }

    @Override
    public UsercountryRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUsercountry from) {
        setUserid(from.getUserid());
        setCountryid(from.getCountryid());
    }

    @Override
    public <E extends IUsercountry> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsercountryRecord
     */
    public UsercountryRecord() {
        super(USERCOUNTRY.USERCOUNTRY);
    }

    /**
     * Create a detached, initialised UsercountryRecord
     */
    public UsercountryRecord(Integer userid, Integer countryid) {
        super(USERCOUNTRY.USERCOUNTRY);

        set(0, userid);
        set(1, countryid);
    }
}
