/*
 * This file is generated by jOOQ.
 */
package cn.qlq.jooq.tables.records;


import cn.qlq.jooq.tables.USER;
import cn.qlq.jooq.tables.interfaces.IUser;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record10<Integer, String, Timestamp, String, String, String, String, String, String, String>, IUser {

    private static final long serialVersionUID = -1290892595;

    /**
     * Setter for <code>test1.user.id</code>.
     */
    @Override
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>test1.user.id</code>.
     */
    @Override
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>test1.user.address</code>.
     */
    @Override
    public void setAddress(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>test1.user.address</code>.
     */
    @Override
    public String getAddress() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test1.user.createtime</code>.
     */
    @Override
    public void setCreatetime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>test1.user.createtime</code>.
     */
    @Override
    public Timestamp getCreatetime() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>test1.user.isdeleted</code>.
     */
    @Override
    public void setIsdeleted(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>test1.user.isdeleted</code>.
     */
    @Override
    public String getIsdeleted() {
        return (String) get(3);
    }

    /**
     * Setter for <code>test1.user.password</code>.
     */
    @Override
    public void setPassword(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>test1.user.password</code>.
     */
    @Override
    public String getPassword() {
        return (String) get(4);
    }

    /**
     * Setter for <code>test1.user.roles</code>.
     */
    @Override
    public void setRoles(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>test1.user.roles</code>.
     */
    @Override
    public String getRoles() {
        return (String) get(5);
    }

    /**
     * Setter for <code>test1.user.sex</code>.
     */
    @Override
    public void setSex(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>test1.user.sex</code>.
     */
    @Override
    public String getSex() {
        return (String) get(6);
    }

    /**
     * Setter for <code>test1.user.userblank</code>.
     */
    @Override
    public void setUserblank(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>test1.user.userblank</code>.
     */
    @Override
    public String getUserblank() {
        return (String) get(7);
    }

    /**
     * Setter for <code>test1.user.userfullname</code>.
     */
    @Override
    public void setUserfullname(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>test1.user.userfullname</code>.
     */
    @Override
    public String getUserfullname() {
        return (String) get(8);
    }

    /**
     * Setter for <code>test1.user.username</code>.
     */
    @Override
    public void setUsername(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>test1.user.username</code>.
     */
    @Override
    public String getUsername() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, Timestamp, String, String, String, String, String, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, String, Timestamp, String, String, String, String, String, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return USER.USER.ID;
    }

    @Override
    public Field<String> field2() {
        return USER.USER.ADDRESS;
    }

    @Override
    public Field<Timestamp> field3() {
        return USER.USER.CREATETIME;
    }

    @Override
    public Field<String> field4() {
        return USER.USER.ISDELETED;
    }

    @Override
    public Field<String> field5() {
        return USER.USER.PASSWORD;
    }

    @Override
    public Field<String> field6() {
        return USER.USER.ROLES;
    }

    @Override
    public Field<String> field7() {
        return USER.USER.SEX;
    }

    @Override
    public Field<String> field8() {
        return USER.USER.USERBLANK;
    }

    @Override
    public Field<String> field9() {
        return USER.USER.USERFULLNAME;
    }

    @Override
    public Field<String> field10() {
        return USER.USER.USERNAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getAddress();
    }

    @Override
    public Timestamp component3() {
        return getCreatetime();
    }

    @Override
    public String component4() {
        return getIsdeleted();
    }

    @Override
    public String component5() {
        return getPassword();
    }

    @Override
    public String component6() {
        return getRoles();
    }

    @Override
    public String component7() {
        return getSex();
    }

    @Override
    public String component8() {
        return getUserblank();
    }

    @Override
    public String component9() {
        return getUserfullname();
    }

    @Override
    public String component10() {
        return getUsername();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getAddress();
    }

    @Override
    public Timestamp value3() {
        return getCreatetime();
    }

    @Override
    public String value4() {
        return getIsdeleted();
    }

    @Override
    public String value5() {
        return getPassword();
    }

    @Override
    public String value6() {
        return getRoles();
    }

    @Override
    public String value7() {
        return getSex();
    }

    @Override
    public String value8() {
        return getUserblank();
    }

    @Override
    public String value9() {
        return getUserfullname();
    }

    @Override
    public String value10() {
        return getUsername();
    }

    @Override
    public UserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UserRecord value2(String value) {
        setAddress(value);
        return this;
    }

    @Override
    public UserRecord value3(Timestamp value) {
        setCreatetime(value);
        return this;
    }

    @Override
    public UserRecord value4(String value) {
        setIsdeleted(value);
        return this;
    }

    @Override
    public UserRecord value5(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UserRecord value6(String value) {
        setRoles(value);
        return this;
    }

    @Override
    public UserRecord value7(String value) {
        setSex(value);
        return this;
    }

    @Override
    public UserRecord value8(String value) {
        setUserblank(value);
        return this;
    }

    @Override
    public UserRecord value9(String value) {
        setUserfullname(value);
        return this;
    }

    @Override
    public UserRecord value10(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public UserRecord values(Integer value1, String value2, Timestamp value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUser from) {
        setId(from.getId());
        setAddress(from.getAddress());
        setCreatetime(from.getCreatetime());
        setIsdeleted(from.getIsdeleted());
        setPassword(from.getPassword());
        setRoles(from.getRoles());
        setSex(from.getSex());
        setUserblank(from.getUserblank());
        setUserfullname(from.getUserfullname());
        setUsername(from.getUsername());
    }

    @Override
    public <E extends IUser> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(USER.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Integer id, String address, Timestamp createtime, String isdeleted, String password, String roles, String sex, String userblank, String userfullname, String username) {
        super(USER.USER);

        set(0, id);
        set(1, address);
        set(2, createtime);
        set(3, isdeleted);
        set(4, password);
        set(5, roles);
        set(6, sex);
        set(7, userblank);
        set(8, userfullname);
        set(9, username);
    }
}
